from scratch

COPY ./docker-compose.yaml /docker-compose.yaml
COPY ./workload-config.json /workload-config.json
COPY ./workload-config.yaml /workload-config.yaml
COPY ./log4j.properties /log4j.properties
